#!/usr/bin/env python3
"""Plot evaluation CSVs generated by tools/run.py.

Usage:
    python3 tools/plot_results.py tools/results/<batch-dir>

The script writes PNG figures to <batch-dir>/figs/.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import pandas as pd  # type: ignore[import-untyped]
import seaborn as sns  # type: ignore[import-untyped]


FIGSIZE = (4, 3)


def main() -> int:
    args = parse_args()
    batch_dir = Path(args.result_dir).resolve()
    sns.set_theme(style="whitegrid", context="notebook")
    plot_all(batch_dir, pd, plt, sns, mticker)
    figs_dir = batch_dir / "figs"
    print(f"Graficos salvos em: {figs_dir}")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate plots for an evaluation result folder.")
    parser.add_argument("result_dir", help="pasta da bateria gerada por tools/run_eval.py")
    return parser.parse_args()


def load_dataset(result_dir: Path, pd):
    result_dir = Path(result_dir).resolve()
    if not result_dir.is_dir():
        raise FileNotFoundError(f"Pasta de resultados nao encontrada: {result_dir}")

    paths = {
        "matches": result_dir / "matches.csv",
        "summary": result_dir / "summary.csv",
        "best_worst": result_dir / "best_worst.csv",
    }
    missing = [str(path) for path in paths.values() if not path.exists()]
    if missing:
        raise FileNotFoundError("CSVs ausentes: " + ", ".join(missing))

    data = {name: pd.read_csv(path) for name, path in paths.items()}
    normalize_frames(data["matches"], data["summary"], data["best_worst"])
    return data


def plot_all(result_dir: Path, pd, plt, sns, mticker, *, close: bool = True) -> Path:
    result_dir = Path(result_dir).resolve()
    dataset = load_dataset(result_dir, pd)
    figs_dir = result_dir / "figs"
    figs_dir.mkdir(exist_ok=True)

    plot_score_distribution(dataset["matches"], figs_dir, plt, sns, close=close)
    plot_win_rates(dataset["summary"], figs_dir, plt, sns, close=close)
    plot_outcomes(dataset["matches"], figs_dir, plt, sns, close=close)
    plot_score_over_rounds(dataset["matches"], figs_dir, plt, sns, mticker, close=close)
    plot_key_metrics(dataset["matches"], figs_dir, plt, sns, pd, close=close)
    plot_loss_reasons(dataset["matches"], figs_dir, plt, sns, close=close)
    plot_best_worst(dataset["summary"], figs_dir, plt, sns, pd, close=close)
    plot_score_vs_exposure(dataset["matches"], figs_dir, plt, sns, close=close)
    return figs_dir


def normalize_frames(matches, summary, best_worst) -> None:
    for frame in [matches, summary, best_worst]:
        for col in ["thief_agent", "detective_agent", "scenario"]:
            if col in frame.columns:
                frame[col] = frame[col].astype(str)

    if "winner" in matches.columns:
        matches["winner"] = matches["winner"].map({
            "ladrao": "thief",
            "detetive": "detective",
            "empate": "draw",
        }).fillna(matches["winner"])


def savefig(path: Path, plt, *, close: bool = True) -> None:
    plt.tight_layout()
    plt.savefig(path, dpi=160, bbox_inches="tight")
    if close:
        plt.close()


def without_all(summary):
    if "detective_agent" not in summary.columns:
        return summary
    filtered = summary[summary["detective_agent"] != "ALL"]
    return filtered if not filtered.empty else summary


def comparison_axis(frame):
    if "thief_agent" in frame.columns and frame["thief_agent"].nunique() > 1:
        return "thief_agent", "Ladrao"
    return "detective_agent", "Detetive"


def plot_score_distribution(matches, figs_dir: Path, plt, sns, *, close: bool = True) -> None:
    x_col, x_label = comparison_axis(matches)
    plt.figure(figsize=FIGSIZE)
    sns.boxplot(data=matches, x=x_col, y="score", color="#7aa6c2")
    sns.stripplot(data=matches, x=x_col, y="score", color="#263238", alpha=0.55, jitter=0.25, size=4)
    plt.title(f"Distribuicao do score por {x_label.lower()}")
    plt.xlabel(x_label)
    plt.ylabel("Score PEAS")
    plt.xticks(rotation=25, ha="right")
    savefig(figs_dir / f"score_distribution_by_{x_col}.png", plt, close=close)


def plot_win_rates(summary, figs_dir: Path, plt, sns, *, close: bool = True) -> None:
    data = without_all(summary).copy()
    x_col, x_label = comparison_axis(data)
    plt.figure(figsize=FIGSIZE)
    ax = sns.barplot(data=data, x=x_col, y="win_rate", color="#4c956c")
    plt.title(f"Taxa de vitoria por {x_label.lower()}")
    plt.xlabel(x_label)
    plt.ylabel("Win rate")
    plt.ylim(0, 1)
    ax.axhline(0, color="#333333", linewidth=0.8)
    for idx, row in data.reset_index(drop=True).iterrows():
        value = float(row["win_rate"])
        label_y = value + 0.03 if value > 0 else 0.04
        ax.text(idx, label_y, f"{value:.2f}", ha="center", va="bottom", fontsize=8)
        if value == 0:
            ax.scatter([idx], [0], color="#4c956c", s=18, zorder=3)
    plt.xticks(rotation=25, ha="right")
    savefig(figs_dir / f"win_rate_by_{x_col}.png", plt, close=close)


def plot_outcomes(matches, figs_dir: Path, plt, sns, *, close: bool = True) -> None:
    x_col, x_label = comparison_axis(matches)
    data = matches.groupby([x_col, "winner"]).size().reset_index(name="count")
    plt.figure(figsize=FIGSIZE)
    sns.barplot(data=data, x=x_col, y="count", hue="winner")
    plt.title(f"Resultados por {x_label.lower()}")
    plt.xlabel(x_label)
    plt.ylabel("Partidas")
    plt.xticks(rotation=25, ha="right")
    plt.legend(title="Resultado")
    savefig(figs_dir / f"outcomes_by_{x_col}.png", plt, close=close)


def plot_score_over_rounds(matches, figs_dir: Path, plt, sns, mticker, *, close: bool = True) -> None:
    hue_col, hue_label = comparison_axis(matches)
    plt.figure(figsize=FIGSIZE)
    ax = sns.lineplot(data=matches, x="round", y="score", hue=hue_col, marker="o", errorbar=None)
    plt.title("Score por rodada")
    plt.xlabel("Rodada")
    plt.ylabel("Score PEAS")
    ax.xaxis.set_major_locator(mticker.MaxNLocator(integer=True))
    plt.legend(title=hue_label)
    savefig(figs_dir / "score_over_rounds.png", plt, close=close)


def plot_key_metrics(matches, figs_dir: Path, plt, sns, pd, *, close: bool = True) -> None:
    metrics = [
        "turns_spent",
        "robberies",
        "real_revealed_attrs",
        "risk",
        "no_progress_moves",
        "illegal_actions",
        "disguises_used",
    ]
    available = [col for col in metrics if col in matches.columns]
    if not available:
        return

    group_col, group_label = comparison_axis(matches)
    melted = matches.melt(
        id_vars=[group_col],
        value_vars=available,
        var_name="metric",
        value_name="value",
    )
    plt.figure(figsize=FIGSIZE)
    sns.barplot(data=melted, x="metric", y="value", hue=group_col, estimator="mean", errorbar=None)
    plt.title(f"Metricas medias por {group_label.lower()}")
    plt.xlabel("Metrica")
    plt.ylabel("Media")
    plt.xticks(rotation=25, ha="right")
    plt.legend(title=group_label)
    savefig(figs_dir / f"mean_metrics_by_{group_col}.png", plt, close=close)


def plot_loss_reasons(matches, figs_dir: Path, plt, sns, *, close: bool = True) -> None:
    if "loss_reason" not in matches.columns:
        return
    data = matches[matches["loss_reason"].fillna("") != ""]
    if data.empty:
        return
    x_col, x_label = comparison_axis(matches)
    counts = data.groupby([x_col, "loss_reason"]).size().reset_index(name="count")
    plt.figure(figsize=FIGSIZE)
    sns.barplot(data=counts, x=x_col, y="count", hue="loss_reason")
    plt.title("Motivos de derrota")
    plt.xlabel(x_label)
    plt.ylabel("Partidas")
    plt.xticks(rotation=25, ha="right")
    plt.legend(title="Motivo")
    savefig(figs_dir / "loss_reasons.png", plt, close=close)


def plot_best_worst(summary, figs_dir: Path, plt, sns, pd, *, close: bool = True) -> None:
    needed = {"detective_agent", "score_best", "score_mean", "score_worst"}
    if not needed.issubset(summary.columns):
        return
    data = without_all(summary).copy()
    x_col, x_label = comparison_axis(data)
    data = data.melt(
        id_vars=[x_col],
        value_vars=["score_best", "score_mean", "score_worst"],
        var_name="kind",
        value_name="score",
    )
    data["kind"] = pd.Categorical(
        data["kind"],
        categories=["score_worst", "score_mean", "score_best"],
        ordered=True,
    )
    labels = {
        "score_worst": "pior",
        "score_mean": "media",
        "score_best": "melhor",
    }
    data["kind"] = data["kind"].map(labels)
    plt.figure(figsize=FIGSIZE)
    sns.barplot(data=data, x=x_col, y="score", hue="kind")
    plt.title("Pior, media e melhor score")
    plt.xlabel(x_label)
    plt.ylabel("Score PEAS")
    plt.xticks(rotation=25, ha="right")
    plt.legend(title="")
    savefig(figs_dir / "best_worst_scores.png", plt, close=close)


def plot_score_vs_exposure(matches, figs_dir: Path, plt, sns, *, close: bool = True) -> None:
    x_col = "real_revealed_attrs" if "real_revealed_attrs" in matches.columns else "revealed_attrs_total"
    if x_col not in matches.columns:
        return
    hue_col, hue_label = comparison_axis(matches)
    plt.figure(figsize=FIGSIZE)
    sns.scatterplot(data=matches, x=x_col, y="score", hue=hue_col, style="winner", s=90)
    plt.title("Score vs exposicao de pistas")
    plt.xlabel(x_col)
    plt.ylabel("Score PEAS")
    plt.legend(title=f"{hue_label} / resultado")
    savefig(figs_dir / "score_vs_exposure.png", plt, close=close)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        raise SystemExit(130)
